version: '3.8'

services:
  fleet_master_main:
    image: fleet_master_main_project:${FLEET_MAIN_BUILD_ID}
    container_name: fleet_master_main
    depends_on:
     - postgres
   #   - elasticsearch
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
   #   - LOGGING_ELASTICSEARCH_URL=${LOGGING_ELASTICSEARCH_URL}
    ports:
      - "8088:8088"
    #volumes:
    #  - logs-volume:/var/log/fleet-master
    networks:
      - fleet-network

  fleet_master_auth:
    image: fleet_master_auth_project:${FLEET_AUTH_BUILD_ID}
    container_name: fleet_master_auth
    depends_on:
      - postgres
 #     - elasticsearch
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
  #    - LOGGING_ELASTICSEARCH_URL=${LOGGING_ELASTICSEARCH_URL}
    ports:
      - "8087:8087"
   # volumes:
    #  - logs-volume:/var/log/fleet-auth
    networks:
      - fleet-network
      
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - fleet-network
      
networks:
  fleet-network:
    driver: bridge
